language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing need to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t kubernetes-on-aws .
  - docker tag kubernetes-on-aws jeskii/kubernetes-on-aws:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jeskii/kubernetes-on-aws
